#!/bin/bash
###this script takes a species-name,location file as inout (coord-list.txt)then it goes to the file location
### opens optimized geometry in Molden, the user is expected to make a list of atoms indices he want to get the 
##charge spin data for from Orca.out
## next user quits molden, writes indices separated by space.
p=`pwd`
for j in `seq 1 13`;
do
a=`head -n $j coord-list.txt | tail -1 | cut -d',' -f1`
b=`head -n $j coord-list.txt | tail -1 | cut -d',' -f2`
cd $b
rm -f charge-spin.txt
pwd
s=`sed -n '/LOEWDIN REDUCED ORBITAL CHARGES AND SPIN POPULATIONS/=' Orca.out | tail -1`
t=`sed -n '/MAYER POPULATION ANALYSIS/=' Orca.out | tail -1`
sed -n "$s","$t"p Orca.out > charge-spin.txt
`molden Orca.xyz`
read atoms    ##here give an input like 1 3 4 7 52   (for spin and charge data for atoms 1, 3,4,5 and 52)
for k in $atoms
do
 i=$((k-1))
 x_k=$((k+2))
 atom=`head -$x_k Orca.xyz | tail -1 | cut -c1-4`    ##3this reads the corresponding atomic symbol from Orca.xyz
 echo $atom,$k >> $p/CS_$a.txt
 if [[ $atom == *"Fe"* ]]       ##cutomize this line, if the arom is "fe" it gives information about 'd' orbital
 then
  charge=`grep -A 4 " $i " charge-spin.txt | grep ' d :' | head -1 | cut -c30-46`
  spin=`grep -A 4 " $i " charge-spin.txt | grep ' d :' | head -2 | tail -1 | cut -c30-46`
 else
  charge=`grep -A 4 " $i " charge-spin.txt | grep ' p :' | head -1 | cut -c30-46`     ###if not "Fe" take info about p orbital
  spin=`grep -A 4 " $i " charge-spin.txt | grep ' p :' | head -2 | tail -1 | cut -c30-46`
 fi
 echo "CHARGE ="$charge >> $p/CS_$a.txt
 echo "SPIN ="$spin >> $p/CS_$a.txt
done
cd $p
done
